version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - mongo_db
      - redis
    env_file:
      - ".env"
    container_name: app
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_db

