version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on:
      - mongo_db
      - redis
    env_file:
      - ".env"
    container_name: app
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URI=mongodb://mongo_db:27017/demo
      - NODE_ENV=development
      - BASE_URL=localhost:3009

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo_db

